### ISSUE TITLE
Status of socket_create() call is masked

### ISSUE THREAD

**Issue by neikos** [orientechnologies/PhpOrient#10]
Is there any reason why the call to socket_create() is masked (prepended with an '@' symbol) on line 78 in file PhpOrient/src/PhpOrient/Protocols/Binary/OrientSocket.php?

My call to $client->connect() failed silently and only after stepping through the PhpOrient code did I find that a compilation of php needs the '--enable-sockets' flag in order to work with PhpOrient.

**Comment by Ostico** [comment]
Hi @neikos ,

you right, the sockets extension must be enabled to work with the driver ( this is pretty obvious i think ), but the socket extension is enabled by default in the php generic installation so i forgotten to mention.

Thank you i will add to the documentation.
