### ISSUE TITLE
FetchPlan not working

### ISSUE THREAD

**Issue by irshadhasmat** [orientechnologies/PhpOrient#11]
Hi Team,

I am trying to use fetchplan but its not working. 

```$return= $client->query('select from make',1,'*:2');```

Do m doing something wrong. Tried various option but no luck.

Thanks.

**Comment by bazo** [comment]
i got the same issue. using *:-1 should fetch all linked data, but i still get just rids out of the query, which is kinda useless as i have to query again for the linked records

**Comment by Ostico** [comment]
Moved to:

https://github.com/Ostico/PhpOrient/issues/50
