### ISSUE TITLE
ostico/phporient socket connection error in centos

### ISSUE THREAD

**Issue by jackraj88** [orientechnologies/PhpOrient#13]
HI,

I am using ostico/phporient official driver it will work fine in windows but not working in centos.

The below error was thrown.

Fatal error: Uncaught exception 'PhpOrient\Exceptions\SocketException' with message 'Error 111 : Connection refused ' in /home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/OrientSocket.php:86 Stack trace: #0 /home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(138): PhpOrient\Protocols\Binary\OrientSocket->connect() #1 /home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php(73): PhpOrient\Protocols\Binary\SocketTransport->getSocket() #2 /home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(174): PhpOrient\Protocols\Binary\Abstracts\Operation->__construct(Object(PhpOrient\Protocols\Binary\SocketTransport)) #3 /home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(153): PhpOrient\Protocols in/home/jackraj/public_html/application/third_party/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/OrientSocket.phpon line 86

Please help asap.

**Comment by smolinari** [comment]
Looks like the connection to the database is not working. Is OrientDB running? Are the credentials definitely correct? 

Scott

**Comment by jackraj88** [comment]
Database is working and same credentials working in  windows environment but not in centos.

jack

**Comment by smolinari** [comment]
Can you access the database through Studio with the same credentials?

Scott

**Comment by jackraj88** [comment]
Yes

Jack

**Comment by jackraj88** [comment]
yes, i can access through studio with same crendentials.

jack

**Comment by smolinari** [comment]
Which versions of ODB, CentOS and PHPOrient are you using? I'll try to build a VM with those versions and see if I can get the tests to run. 

Scott

**Comment by jackraj88** [comment]
Linux sg2plcpnl0057.prod.sin2.secureserver.net 2.6.32-531.29.2.lve1.3.11.10.el6.x86_64
odb - 1.7.2
phporient - 1.0.0

jack

**Comment by smolinari** [comment]
Thanks. Is there a particular reason why you are still on these old versions? PHPOrient is at 1.2.0 and ODB is at Version 2.1.4. Usually the first reply to such old versions would be...please upgrade. 

Scott
