### ISSUE TITLE
Protocol version 36 is not supported

### ISSUE THREAD

**Issue by 0xfff** [orientechnologies/PhpOrient#14]
i get this error trying to connect:

> PHP Fatal error:  Uncaught exception 'PhpOrient\Exceptions\PhpOrientWrongProtocolVersionException' with message '**Protocol version 36 is not supported**.' in /home2/WORK/BTGI/Clustering/CODE/PhpOrient-1.2.1/src/PhpOrient/Protocols/Binary/OrientSocket.php:92

**Comment by smolinari** [comment]
It's being worked on here. https://github.com/Ostico/PhpOrient/issues/71

Scott

**Comment by Ostico** [comment]
New version available.
