### ISSUE TITLE
Is it possible to run IMPORT DATABASE command in PhpOrient?

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/PhpOrient#15]
The connection is working correctly and I have the database selected.

`$client->dbOpen('dbName');`

All works until I try to run the command:

`$client->command('IMPORT DATABASE /path/to/file/export.gz');`
When I get this exception:

```
Message: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.IMPORT DATABASE /path/to/file/export.gz -preserveClusterIDs=true DB name="dbname"
```

If the command command is not correct, then what can be use instead?

**Comment by Ostico** [comment]
Hi @igasparetto ,
unfortunately, the binary protocol does not support import statement.
You can use the orient console instead:
http://orientdb.com/docs/2.1/Console-Command-Import.html

**Comment by igasparetto** [comment]
Hi @Ostico 

That is a shame!

Is there any plans for developing such functionality?

Thanks

**Comment by Ostico** [comment]
Hi @igasparetto ,
sorry but this is not dependant on my driver. You should ask to the OrientDB developers.
