### ISSUE TITLE
No support for OrientDB3.0 but it actually works

### ISSUE THREAD

**Issue by futureglorydev** [orientechnologies/PhpOrient#19]
If you try to use new orientdb 3.0 i will get an error. But all you need to do is to change protocol version in constants to 37.  Basic features work.
Will the library support new orinetdb 3?

**Comment by Ostico** [comment]
Hi @futureglorydev ,
need time to test, much things changed from version 2. It should be not only a matter of constants :)

**Comment by futureglorydev** [comment]
Thanks @Ostico !
looking forward with optimistic view on orient3 full support!

**Comment by usef911** [comment]
Hi @Ostico 
Are you still maintaining this driver?

**Comment by Ostico** [comment]
Yes, but unfortunately, my time is really limited at moment

**Comment by Krienas** [comment]
Btw @Ostico which repository we should actually use? orientechnologies/PhpOrient (which is actually very old fork of Ostico/PhpOrient) or Ostico/PhpOrient which has more recent changes while still being old..

**Comment by Ostico** [comment]
@Krienas Ostico/PhpOrient is the most updated one

**Comment by ckiyici** [comment]
the problem still going on?

**Comment by Ostico** [comment]
New release available.
