### ISSUE TITLE
Question | SQL injection

### ISSUE THREAD

**Issue by Nirlah** [orientechnologies/PhpOrient#2]
Hi,

What is the preferred method to prevent SQL injections using this library?

Thanks :grinning:

**Comment by Ostico** [comment]
In the next version of OrientDB it should be present.

**Comment by cqcwillard** [comment]
I believe OrientDB only supports client side prepared statements at the moment, is this the case?  The NodeJS library appears to be encoding the values on the client side as well.

Reference:
https://github.com/codemix/oriento/blob/master/lib/transport/binary/protocol28/operations/command.js

**Comment by Ostico** [comment]
Tes @cqcwillard , you're right.

There are no way to perform prepared statement and server side sanitization like PDO and MySQL does.

I'm planning to add a PDO like interface to this driver and implement client side the prepared statement object.

**Comment by douggard** [comment]
I was really excited to try out OrientDB. This is pretty much a non-starter for me though. Security features are super important, they should be supported server side and not reimplemented in each client.
