### ISSUE TITLE
Exception after command ALTER PROPERTY 

### ISSUE THREAD

**Issue by nicolapetracchi** [orientechnologies/PhpOrient#7]
After an ALTER PROPERTY command is executed all others commands / query executed results with a raised exception:

    PhpOrient\Exceptions\PhpOrientException: Unknown payload type H in ..\PhpOrient\Protocols\Binary\Abstracts\Operation.php on line 577

... the command is successfully executed on the server, I can see the changes on the schema, unfortunately I can't get a result no more due the raised error, this then makes query commands useless.

So for example
->query('select ...'); # execution OK, result OK
->command('ALTER PROPERTY ...'); # execution OK, result OK
->command('ALTER PROPERTY ...'); # execution OK, result Exception
->query('select ...'); # execution OK, result Exception

Tested on:
orientdb 2.0.5 ubuntu php 5.4.39 & windows 7 php 5.4.38
orientdb 2.0.6 windows 7 php 5.4.38

**Comment by Ostico** [comment]
Moved here:
https://github.com/Ostico/PhpOrient/issues/23
